"""add latitude and longitude to evacuee_family

Revision ID: 531984181bf8
Revises: 3415f39061a6
Create Date: 2026-03-30 14:24:06.185862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531984181bf8'
down_revision: Union[str, Sequence[str], None] = '3415f39061a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evacuee_family', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('evacuee_family', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evacuee_family', 'longitude')
    op.drop_column('evacuee_family', 'latitude')
    # ### end Alembic commands ###
