"""initial

Revision ID: eff41b5f100c
Revises: 
Create Date: 2026-03-18 18:36:47.612268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff41b5f100c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('user_role', sa.Enum('HOST', 'EVACUEE', 'ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_role'), 'users', ['user_role'], unique=False)
    op.create_table('admin_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_profile_user_id'), 'admin_profile', ['user_id'], unique=True)
    op.create_table('evacuee_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_size', sa.Integer(), nullable=False),
    sa.Column('origin_city', sa.String(length=255), nullable=False),
    sa.Column('special_needs', sa.String(length=500), nullable=True),
    sa.Column('needs_accessibility', sa.Boolean(), nullable=False),
    sa.Column('documents_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='family_verification_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evacuee_family_user_id'), 'evacuee_family', ['user_id'], unique=True)
    op.create_index(op.f('ix_evacuee_family_verification_status'), 'evacuee_family', ['verification_status'], unique=False)
    op.create_table('host_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('documents_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verification_status_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_profile_user_id'), 'host_profile', ['user_id'], unique=True)
    op.create_index(op.f('ix_host_profile_verification_status'), 'host_profile', ['verification_status'], unique=False)
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('specific_tags', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='property_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_profile_id'], ['host_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_host_profile_id'), 'property', ['host_profile_id'], unique=False)
    op.create_index(op.f('ix_property_status'), 'property', ['status'], unique=False)
    op.create_table('availability_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('slot_status', sa.Enum('AVAILABLE', 'BLOCKED', 'BOOKED', name='slot_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_slot_property_id'), 'availability_slot', ['property_id'], unique=False)
    op.create_table('booking_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('requested_start_date', sa.Date(), nullable=False),
    sa.Column('requested_end_date', sa.Date(), nullable=False),
    sa.Column('requested_capacity', sa.Integer(), nullable=False),
    sa.Column('family_message', sa.String(length=1000), nullable=True),
    sa.Column('request_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='request_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('host_response', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['evacuee_family.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_request_family_id'), 'booking_request', ['family_id'], unique=False)
    op.create_index(op.f('ix_booking_request_property_id'), 'booking_request', ['property_id'], unique=False)
    op.create_index(op.f('ix_booking_request_request_status'), 'booking_request', ['request_status'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_request_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_request_id'], ['booking_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_related_request_id'), 'notification', ['related_request_id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['evacuee_family.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['booking_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_family_id'), 'review', ['family_id'], unique=False)
    op.create_index(op.f('ix_review_property_id'), 'review', ['property_id'], unique=False)
    op.create_index(op.f('ix_review_request_id'), 'review', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_request_id'), table_name='review')
    op.drop_index(op.f('ix_review_property_id'), table_name='review')
    op.drop_index(op.f('ix_review_family_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_related_request_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_booking_request_request_status'), table_name='booking_request')
    op.drop_index(op.f('ix_booking_request_property_id'), table_name='booking_request')
    op.drop_index(op.f('ix_booking_request_family_id'), table_name='booking_request')
    op.drop_table('booking_request')
    op.drop_index(op.f('ix_availability_slot_property_id'), table_name='availability_slot')
    op.drop_table('availability_slot')
    op.drop_index(op.f('ix_property_status'), table_name='property')
    op.drop_index(op.f('ix_property_host_profile_id'), table_name='property')
    op.drop_table('property')
    op.drop_index(op.f('ix_host_profile_verification_status'), table_name='host_profile')
    op.drop_index(op.f('ix_host_profile_user_id'), table_name='host_profile')
    op.drop_table('host_profile')
    op.drop_index(op.f('ix_evacuee_family_verification_status'), table_name='evacuee_family')
    op.drop_index(op.f('ix_evacuee_family_user_id'), table_name='evacuee_family')
    op.drop_table('evacuee_family')
    op.drop_index(op.f('ix_admin_profile_user_id'), table_name='admin_profile')
    op.drop_table('admin_profile')
    op.drop_index(op.f('ix_users_user_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
