"""add latitude and longitude to property

Revision ID: f8cbf22ac3ea
Revises: 531984181bf8
Create Date: 2026-03-30 15:33:55.591040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8cbf22ac3ea'
down_revision: Union[str, Sequence[str], None] = '531984181bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('property', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'longitude')
    op.drop_column('property', 'latitude')
    # ### end Alembic commands ###
